services:
  - type: web
    name: cryptinsa-app
    env: docker
    region: frankfurt # ou oregon, singapore selon votre préférence
    plan: free # ou starter pour plus de ressources
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    # Render détecte automatiquement le port via la variable $PORT
    # healthCheckPath: / # optionnel: endpoint pour vérifier la santé de l'app 